apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "another-artist-web"
  namespace: default
  title: "arz-test"
  description: "Description after removing required field"
  labels:
    environment: prod
    organization: yamaha
  annotations:
    Source-location: "url:https://github.com/Efi4/backstage/edit/main/component.yaml"
    Owner: "arz@sitecore.net"
    Lifecycle: experimental
    Type: service
  tags: ['one','two','three']
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  lifecycle: production
  type: website
  owner: "artist-relations-team"
  system: "artist-engagement-portal"
  dependsOn:
    - "Component:default/podcast-api"
  providesApis:
    - "artist-api"
  subcomponentOf: "Component:default/searcher"
  consumesApis:
    - "vim-artist-web"
