apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "artist-web"
  namespace: namespace
  title: title
  description: "New description"
  labels:
    environment: prod
    organization: yamaha
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/backstage/backstage/tree/master/packages/catalog-model/examples/components/wayback-search-component.yaml"
  tags: ['one','two','three']
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: website
  lifecycle: production
  owner: "artist-relations-team"
  system: "artist-engagement-portal"
  dependsOn:
    - "resource:default/artists-db"
  providesApis:
    - ""resource:default/artist-api"
  subcomponentOf: "resource:default/searcher"
  consumesApis:
    - "resource:default/vim-artist-web
