apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "inventory"
  namespace: default
  title: "Inventory component"
  description: "The inventory component provides API"
  labels:
    environment: dev
    organization: sitecore
  annotations:
    Source-location: "url:https://github.com/Efi4/backstage/blob/main/inventory_comp.yaml"
    Owner: group:default/grp_-_platform_experience_team
    Lifecycle: experimental
    Type: service
  tags: ['inventory','dev']
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  owner: group:default/grp_-_platform_experience_team
  lifecycle: development
  type: component
  system: "inventory-system"
  providesApis:
    - "inventory-api"
