apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platform-tas_api
  title: Tenant Activation Service API
  description: The Tenant Activation Service component that is responsible for managing all the provisioning and deprovisioning of edge, mds and public collections tenants.
  annotations:
    backstage.io/source-location: url:https://bitbucket.org/stylelabsdev/sitecore.platform.tas/src/main/
    backstage.io/view-url: url:https://bitbucket.org/stylelabsdev/sitecore.platform.tas/src/main/src/Sitecore.Platform.TAS.API/catalog-info.yaml
  tags: ['csharp']
  links:
    - url: https://tas-webapi-dev.sitecore-staging.cloud
      title: Tenant Activation Service API - dev
      icon: cloud
    - url: https://tas-webapi-staging.sitecore-staging.cloud
      title: Tenant Activation Service API - staging
      icon: cloud
    - url: https://tas-webapi-pre-prod.sitecorecloud.io
      title: Tenant Activation Service API - pre-production
      icon: cloud
    - url: https://tas-webapi-prod.sitecorecloud.io
      title: Tenant Activation Service API - production
      icon: cloud
    - url: https://stylelabs.atlassian.net/jira/software/c/projects/PRODOT/boards/480
      title: _Inbox
      icon: dashboard
spec:
  owner: group:default/grp_-_platform_-_platform_experience_-_be
  lifecycle: production
  type: service
  system: platform
  providesApis:
    - platform-tas_api-api-v1
  dependsOn: ['system:identity']
