apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: breanna.davison
spec:
  profile:
    # Intentional no displayName for testing
    email: breanna-davison@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [arz-test-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: janelle.dawe
spec:
  profile:
    displayName: Janelle Dawe
    email: janelle-dawe@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [arz-test-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nigel.manning
spec:
  profile:
    displayName: Nigel Manning
    email: nigel-manning@example.com
    picture: https://avatars.dicebear.com/api/avataaars/nigel-manning@example.com.svg?background=%23fff
  memberOf: [arz-test-team]
 ---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: artem.zyma
spec:
  profile:
    displayName: Artem Zyma
    email: artem.zyma@sitecore.com
    picture: https://www.google.com/imgres?imgurl=https%3A%2F%2Fsitecorecdn.azureedge.net%2F-%2Fmedia%2Fsitecoresite%2Fimages%2Fglobal%2Flogo%2Fsitecore-logo.svg&imgrefurl=https%3A%2F%2Fwww.sitecore.com%2F&tbnid=Qkjx6S0Qj3gQyM&vet=12ahUKEwjPs6TfvtL3AhXWtSoKHcnpBMsQMygAegUIARCnAQ..i&docid=5GaONyta2a6ZpM&w=800&h=178&q=sitecore%20logo%20url&ved=2ahUKEwjPs6TfvtL3AhXWtSoKHcnpBMsQMygAegUIARCnAQ
  memberOf: [arz-test-team]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [arz-test-team]
